[package]
name = "memoparsa"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "*"
chrono-tz = "*"
lazy_static = "*"
log = "0.4.6"
env_logger = "0.6.1"
maplit = "*"

[dev-dependencies]
